
spring:
  application:
    name: votacao
    
  datasource:
    url: jdbc:mysql://desafio.cr634eqehebm.us-east-1.rds.amazonaws.com:3306/desafio-act
    username: root
    password: 36731249
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 

server:
  port: 5000
  
  

  
 
      

      